### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by steff2632** [54mv39/web#2]
Hey

Why not issue a pull request on the transmission repo for this? Get it into the main web client

**Comment by 54mv39** [comment]
Yeah.. will do..

**Comment by 54mv39** [comment]
Transmission team has updated many things in the webui actually.. and I did this a long time back.. 

But i do have this in the back of my mind and will do it as and when I get the time.

**Comment by Nicolasoo7** [comment]
> Transmission team has updated many things in the webui actually.. and I did this a long time back..
> 
> But i do have this in the back of my mind and will do it as and when I get the time.

Interested too, nice functionnality.

Your functionnality add the possibility to add tracker. Also to delete ?

**Comment by 54mv39** [comment]
> > Transmission team has updated many things in the webui actually.. and I did this a long time back..
> > But i do have this in the back of my mind and will do it as and when I get the time.
> 
> Interested too, nice functionnality.
> 
> Your functionnality add the possibility to add tracker. Also to delete ?

For deletion of tracker the Transmission repo already has issues. Deletion requires rpc source changes, my functionality is only aimed at exposing the already exisiting tracker add functionality to the limited web UI.

**Comment by 54mv39** [comment]
.--
