### ISSUE TITLE
can not work at centos7 Transmission 3.00 (bb6b5a062e)  

### ISSUE THREAD

**Issue by samlin39** [54mv39/web#3]
![image](https://user-images.githubusercontent.com/46712710/101246879-e8592600-3750-11eb-93d0-62933105b97e.png)
click and no response

**Comment by 54mv39** [comment]
Looks like an installation issue... please re-install and check.

**Comment by samlin39** [comment]
> Looks like an installation issue... please re-install and check.

thanks
